#!/usr/bin/env python3
"""
Bridge classified attack pcaps to normalized attack jobs and selected incremental
AntiDDoS1908 templates.

Workflow:
1. read the classifier output directory
2. normalize each classified pcap into one attack_type via policy_mapper.py
3. deduplicate jobs by victim_ip + attack_type, keeping the larger classified pcap
4. map attack_type to the corresponding incremental template JSON
5. emit selected template files plus a manifest for downstream dispatch
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from huawei_dispatcher import safe_name
from policy_mapper import classify_file


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TEMPLATE_DIR = PROJECT_ROOT / "华为antiddos1908/模板/switch_templates_incremental"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "workdir/incremental_templates"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('classified_root', help='Root directory generated by ddos_classifier_v5_2.py')
    parser.add_argument(
        '--template-dir',
        default=str(DEFAULT_TEMPLATE_DIR),
        help='Directory containing incremental attack templates',
    )
    parser.add_argument(
        '--output-dir',
        default=str(DEFAULT_OUTPUT_DIR),
        help='Directory for selected incremental templates and manifests',
    )
    parser.add_argument(
        '--jobs-output',
        default=None,
        help='Optional JSONL output path for normalized policy jobs',
    )
    return parser.parse_args()


def build_jobs(root: Path) -> list[dict[str, Any]]:
    pcap_files = sorted(root.rglob('*.pcap'))
    if not pcap_files:
        raise SystemExit(f'no pcap files found under: {root}')
    return [asdict(classify_file(path, root)) for path in pcap_files]


def dedupe_jobs(jobs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    selected: dict[tuple[str, str], dict[str, Any]] = {}
    for job in jobs:
        key = (str(job['victim_ip']), str(job['attack_type']))
        current = selected.get(key)
        if current is None or int(job['evidence']['file_size_bytes']) > int(current['evidence']['file_size_bytes']):
            selected[key] = job
    return list(selected.values())


def default_jobs_output(output_dir: Path) -> Path:
    return output_dir / 'policy_jobs.jsonl'


def write_jobs_file(jobs: list[dict[str, Any]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open('w', encoding='utf-8') as fh:
        for job in jobs:
            fh.write(json.dumps(job, ensure_ascii=False) + '\n')


def template_name_for_attack_type(attack_type: str) -> str:
    return f'{attack_type.lower()}.switch_template.incremental.json'


def select_template_for_job(job: dict[str, Any], template_dir: Path, output_dir: Path) -> dict[str, Any]:
    attack_type = str(job['attack_type'])
    source_template = template_dir / template_name_for_attack_type(attack_type)
    if not source_template.exists():
        raise FileNotFoundError(f'missing template for attack_type={attack_type}: {source_template}')

    stem = safe_name(f"{job['job_id']}_{job['attack_type']}_{job['victim_ip']}")
    selected_dir = output_dir / 'selected_templates'
    selected_dir.mkdir(parents=True, exist_ok=True)
    selected_path = selected_dir / f'{stem}.incremental.json'

    payload = json.loads(source_template.read_text(encoding='utf-8'))
    payload['selected_for_job'] = {
        'job_id': job['job_id'],
        'attack_type': job['attack_type'],
        'victim_ip': job['victim_ip'],
        'source_pcap': job['source_pcap'],
        'category': job['category'],
        'confidence': job['confidence'],
        'severity': job['severity'],
    }
    selected_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

    return {
        'job_id': job['job_id'],
        'attack_type': job['attack_type'],
        'victim_ip': job['victim_ip'],
        'source_pcap': job['source_pcap'],
        'category': job['category'],
        'template_source': str(source_template.resolve()),
        'template_output': str(selected_path.resolve()),
    }


def main() -> None:
    args = parse_args()
    classified_root = Path(args.classified_root).resolve()
    template_dir = Path(args.template_dir).resolve()
    output_dir = Path(args.output_dir).resolve()

    if not classified_root.exists():
        raise SystemExit(f'classified root not found: {classified_root}')
    if not template_dir.exists():
        raise SystemExit(f'template dir not found: {template_dir}')

    output_dir.mkdir(parents=True, exist_ok=True)

    all_jobs = build_jobs(classified_root)
    selected_jobs = dedupe_jobs(all_jobs)
    jobs_output = Path(args.jobs_output).resolve() if args.jobs_output else default_jobs_output(output_dir)
    write_jobs_file(selected_jobs, jobs_output)

    selections = [select_template_for_job(job, template_dir, output_dir) for job in selected_jobs]

    manifest = {
        'workflow': [
            'classified pcap -> normalized attack_type',
            'normalized attack_type -> deduplicated job per victim_ip + attack_type',
            'deduplicated attack_type -> incremental template',
            'selected incremental template -> downstream dispatch input',
        ],
        'classified_root': str(classified_root),
        'template_dir': str(template_dir),
        'original_job_count': len(all_jobs),
        'selected_job_count': len(selected_jobs),
        'jobs_output': str(jobs_output),
        'selected_template_count': len(selections),
        'selections': selections,
    }
    manifest_path = output_dir / 'selected_template_manifest.json'
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

    print(json.dumps({
        'original_job_count': len(all_jobs),
        'selected_job_count': len(selected_jobs),
        'jobs_output': str(jobs_output),
        'manifest': str(manifest_path.resolve()),
        'selected_template_count': len(selections),
    }, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
